trigger: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: geo-location.Validate
    source: geo-location.Validate
    trigger: true

stages: 
- stage: Build
  jobs:
  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'public-webapp'
      publishArtifact: true

  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildLookupWebApi'
      projectName: 'lookup-webapi'
      publishArtifact: true

- stage: Packages
  jobs:
  - template: templates/build-net-library.yml
    parameters: 
      jobName: 'PublishLookupApiClient'
      projectName: 'lookup-api-client'
      publishToNuGet: true
      MajorMinorVersion: '1.0'

- stage: DeployPrdPlatform
  jobs:
  - job: DeployPrdPlatformBicep
    steps:
      - task: AzureCLI@2
        displayName: DeployPrdPlatformBicep
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create `
              --template-file bicep/platform.bicep `
              --location 'uksouth' `
              --parameters @params/platform.prd.json

  - job: DeployPrdPlatformPermissions
    dependsOn: [DeployPrdPlatformBicep]
    steps:
      - task: AzureCLI@2
        displayName: SetDeployPrincipalPermissions
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"prd" "uksouth"'
          addSpnToEnvironment: true
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetDeployPrincipalPermissions.ps1'

      - task: AzureCLI@2
        displayName: CreateAppRegistrations
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"prd" "uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateAppRegistrations.ps1'

- stage: DeployPrdServices
  jobs:
  - job: DeployPrdServicesBicep
    steps:
      - task: AzureCLI@2
        displayName: DeployPrdServicesBicep
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create `
              --resource-group 'rg-geolocation-prd-uksouth' `
              --template-file bicep/services.bicep `
              --parameters @params/services.prd.json

  - job: DeployPrdServicePermissions
    dependsOn: [DeployPrdServicesBicep]
    steps:
      - task: AzureCLI@2
        displayName: SetPublicWebAppPermissions
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"prd" "uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetPublicWebAppPermissions.ps1'

  - template: templates/deploy-web-app.yml
    parameters:
      dependsOn: ['DeployPrdServicesBicep']
      projectName: lookup-webapi
      jobName: DeployLookupWebApi
      webAppName: 'webapi-geolocation-lookup-prd-uksouth'
      webAppNameResourceGroup: 'rg-geolocation-prd-uksouth'
      subscription: 'spn-ado-Personal-Public-geolocation-prd'

  - template: templates/deploy-web-app.yml
    parameters:
      dependsOn: ['DeployPrdServicesBicep']
      projectName: public-webapp
      jobName: DeployPublicWebApp
      webAppName: 'webapp-geolocation-public-prd-uksouth'
      webAppNameResourceGroup: 'rg-geolocation-prd-uksouth'
      subscription: 'spn-ado-Personal-Public-geolocation-prd'