trigger: none
pr: none

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux
  pipelines:
  - pipeline: geo-location.Validate
    source: geo-location.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: Build
  jobs:
  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'public-webapp'
      publishArtifact: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildLookupWebApi'
      projectName: 'lookup-webapi'
      publishArtifact: true

- stage: Packages
  jobs:
  - template: jobs/build-net-library.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildLookupApiClient'
      projectName: 'lookup-api-client'
      majorMinorVersion: '1.0'
      publishArtifact: true

  - template: jobs/build-net-library.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildLookupApiAbstractions'
      projectName: 'lookup-api-abstractions'
      majorMinorVersion: '1.0'
      publishArtifact: true

- stage: DeployPackages

  jobs:
  - template: jobs/push-nuget-package.yml@ado-pipeline-templates
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    parameters: 
      jobName: 'PublishLookupApiClient'
      projectName: 'lookup-api-client'
      majorMinorVersion: '1.0'
      packageName: 'MX.GeoLocation.GeoLocationApi.Client'

  - template: jobs/push-nuget-package.yml@ado-pipeline-templates
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    parameters: 
      jobName: 'PublishLookupApiAbstractions'
      projectName: 'lookup-api-abstractions'
      majorMinorVersion: '1.0'
      packageName: 'MX.GeoLocation.LookupApi.Abstractions'

- stage: DeployPrdPlatform
  jobs:

  - deployment: DeployPrdPlatformBicep
    environment: 'geolocation-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: DeployPrdPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  if ($null -eq (az keyvault show --name 'kv-geoloc-prd-uksouth')) { $keyVaultCreateMode = 'default' } else { $keyVaultCreateMode = 'recover' }

                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json `
                      parKeyVaultCreateMode=$keyVaultCreateMode

  - job: DeployPrdPlatformPermissions
    dependsOn: [DeployPrdPlatformBicep]
    steps:
      - task: AzureCLI@2
        displayName: SetDeployPrincipalPermissions
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"prd" "uksouth"'
          addSpnToEnvironment: true
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetDeployPrincipalPermissions.ps1'

      - task: AzureCLI@2
        displayName: CreateAppRegistrations
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"prd" "uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateAppRegistrations.ps1'

      - task: AzureCLI@2
        displayName: CreateAppRegistrationsCredentials
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"prd" "uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateAppRegistrationsCredentials.ps1'


- stage: DeployPrdServices
  jobs:

  - deployment: DeployPrdServicesBicep
    environment: 'geolocation-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: DeployPrdServicesBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create `
                    --resource-group 'rg-geolocation-prd-uksouth' `
                    --template-file bicep/services.bicep `
                    --parameters @params/services.prd.json

  - job: DeployPrdServicePermissions
    dependsOn: [DeployPrdServicesBicep]
    steps:
      - task: AzureCLI@2
        displayName: SetPublicWebAppPermissions
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd-webapps'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"prd" "uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetPublicWebAppPermissions.ps1'

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['DeployPrdServicesBicep']
      environment: 'platform-webapps-prd-uksouth'
      projectName: lookup-webapi
      jobName: DeployLookupWebApi
      webAppName: 'webapi-geolocation-lookup-prd-uksouth'
      webAppNameResourceGroup: 'rg-platform-webapps-prd-uksouth'
      subscription: 'spn-ado-Personal-Public-geolocation-prd-webapps'

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['DeployPrdServicesBicep']
      environment: 'platform-webapps-prd-uksouth'
      projectName: public-webapp
      jobName: DeployPublicWebApp
      webAppName: 'webapp-geolocation-public-prd-uksouth'
      webAppNameResourceGroup: 'rg-platform-webapps-prd-uksouth'
      subscription: 'spn-ado-Personal-Public-geolocation-prd-webapps'

- stage: PostDeploymentTests
  jobs:

  - job: RunUITests
    displayName: 'Run UI Tests'

    variables:
    - name: SITE_URL
      value: 'https://www.geo-location.net'

    steps: 
    - task: UseDotNet@2
      displayName: 'Use .NET SDK 6.x'
      inputs:
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - Release'
      inputs:
        command: 'build'
        arguments: '--configuration Release'
        projects: '$(System.DefaultWorkingDirectory)/**/*.UITests.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run UI Tests'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration Release'
        publishTestResults: true
        projects: '$(System.DefaultWorkingDirectory)/**/*.UITests.csproj'
    
