trigger: none

pool: 'Dedicated'

stages: 
- stage: Build
  jobs:
  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'public-webapp'
      publishArtifact: true

  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildLookupWebApi'
      projectName: 'lookup-webapi'
      publishArtifact: true

- stage: DeployPrdPlatform
  jobs:
  - job: DeployAADResources
    steps:
      - task: AzureCLI@2
        displayName: CreateAppRegistrations
        inputs:
          azureSubscription: 'sub-fm-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: 'prd'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateAppRegistrations.ps1'

  - job: DeployPlatformBicep
    steps:
      - task: AzureCLI@2
        displayName: DeployPlatformBicep
        inputs:
          azureSubscription: 'sub-fm-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create `
              --template-file bicep/platform.bicep `
              --location 'uksouth' `
              --parameters parLocation='uksouth' `
                parEnvironment='prd'

- stage: DeployPrdServices
  jobs:
  - job: DeployPrdServices
    steps:
      - task: AzureCLI@2
        displayName: DeployPrdServices
        inputs:
          azureSubscription: 'sub-fm-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create `
              --resource-group 'rg-geolocation-prd-uksouth' `
              --template-file bicep/services.bicep `
              --parameters parLocation='uksouth' `
                parEnvironment='prd'