trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages: 
- stage: Build
  jobs:
  - template: jobs/dependency-check.yml@ado-pipeline-templates
    parameters: 
      jobName: 'DependencyCheck'
      failOnCVSS: 4

  - template: jobs/build-net-core-projects.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildNetCoreProjects'
      toolsManifestPath: '$(Build.SourcesDirectory)/.config/dotnet-tools.json'
      useCobertura: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'public-webapp'
      publishArtifact: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildLookupWebApi'
      projectName: 'lookup-webapi'
      publishArtifact: true

  - template: jobs/build-net-library.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildLookupApiClient'
      projectName: 'lookup-api-client'
      majorMinorVersion: '1.0'
      publishArtifact: true

  - template: jobs/build-net-library.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildLookupApiAbstractions'
      projectName: 'lookup-api-abstractions'
      majorMinorVersion: '1.0'
      publishArtifact: true

  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-ado-Personal-Public-devtest'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      jobName: 'ValidateBicepAgainstDevEnvironment'
      azureSubscription: 'spn-ado-Personal-Public-devtest'
      environment: 'dev'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      jobName: 'ValidateBicepAgainstPrdEnvironment'
      azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
      environment: 'prd'

- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: 'spn-ado-Personal-Public-devtest'
    webAppsAzureSubscription: 'spn-ado-Personal-Public-devtest'
    environmentFriendlyName: 'Dev'
    environment: 'dev'

- template: templates/execute-ui-tests.yml
  parameters:
    environmentFriendlyName: 'Dev'
    siteUrl: 'https://dev.geo-location.net'

- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: templates/deploy-environment.yml
    parameters:
      azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
      webAppsAzureSubscription: 'spn-ado-Personal-Public-geolocation-prd-webapps'
      environmentFriendlyName: 'Prd'
      environment: 'prd'

- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: templates/execute-ui-tests.yml
    parameters:
      environmentFriendlyName: 'Prd'
      siteUrl: 'https://www.geo-location.net'

- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: templates/deploy-nuget-packages.yml
