pr:
  branches:
    include:
    - '*'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

pool: 'Dedicated'

stages: 
- stage: Validation
  jobs:
  - template: jobs/dependency-check.yml@ado-pipeline-templates
    parameters: 
      jobName: 'DependencyCheck'
      failOnCVSS: 4

  - template: jobs/build-net-core-projects.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildNetCoreProjects'
      toolsManifestPath: '$(Build.SourcesDirectory)/.config/dotnet-tools.json'
      useCobertura: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'public-webapp'
      publishArtifact: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildLookupWebApi'
      projectName: 'lookup-webapi'
      publishArtifact: true
      
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLintCode'
      azureSubscription: 'spn-ado-Personal-Public-devtest'

  - template: templates/bicep-environment-validate.yml
    parameters:
      dependsOn: [BicepLintCode]
      jobName: 'BicepEnvironmentValidationForPrd'
      azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
      environment: 'prd'

stages: 
- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
    environmentFriendlyName: 'Prd'
    environment: 'prd'

- template: templates/execute-ui-tests.yml
  parameters:
    environmentFriendlyName: 'Prd'
    siteUrl: 'https://geo-location.net'
