trigger:
  branches:
    include:
    - '*'

pool: 'Dedicated'

stages: 
- stage: Build
  jobs:
  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'public-webapp'

  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildLookupWebApi'
      projectName: 'lookup-webapi'

- stage: ValidateBicep
  jobs: 
  - job: LintCode
    displayName: Lint Code
    steps:
      - script: |
          az bicep build --file bicep/platform.bicep
          az bicep build --file bicep/services.bicep
        name: LintBicepCode
        displayName: Run Bicep Linter

  - job: ValidateBicepCode
    dependsOn: [LintCode]
    displayName: Validate Bicep Code
    steps:
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run Preflight Validation
        inputs:
          azureSubscription: 'sub-fm-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub validate `
              --template-file bicep/platform.bicep `
              --location 'uksouth' `
              --parameters parLocation='uksouth' `
                parEnvironment='prd' `
                parLogWorkspaceName='log-platform-prd-uksouth'

            az deployment group validate `
              --resource-group 'rg-geolocation-prd-uksouth' `
              --template-file bicep/services.bicep `
              --parameters parLocation='uksouth' `
                parEnvironment='prd'