parameters:
- name: skipBicepValidate
  type: boolean
  default: false

trigger:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

pr:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

pool: 'Dedicated'

stages: 
- stage: Build
  jobs:
  - template: jobs/dependency-check.yml@ado-pipeline-templates
    parameters: 
      jobName: 'DependencyCheck'
      failOnCVSS: 4

  - template: jobs/build-net-core-projects.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildNetCoreProjects'

- stage: ValidateBicep
  jobs: 
  - job: LintCode
    displayName: Lint Code
    steps:
      - task: AzureCLI@2
        name: LintBicepCode
        displayName: Run Bicep Linter
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $files = Get-ChildItem '$(Build.sourcesDirectory)/bicep/*.bicep'

            foreach ($file in $files) {
              Write-Host "Running az bicep build for '$($file.FullName)'"
              az bicep build --file $file.FullName --stdout
            }

  - deployment: ValidateBicepCode
    dependsOn: [LintCode]
    environment: 'geolocation-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              name: RunPreflightValidation
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub validate `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json

                  if ('${{ parameters.skipBicepValidate }}' -eq $false)
                  {
                    az deployment group validate `
                      --resource-group 'rg-geolocation-prd-uksouth' `
                      --template-file bicep/services.bicep `
                      --parameters @params/services.prd.json
                  }

            - task: AzureCLI@2
              name: RunWhatIfDeploy
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub what-if `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json

                  if ('${{ parameters.skipBicepValidate }}' -eq $false)
                  {
                    az deployment group what-if `
                      --resource-group 'rg-geolocation-prd-uksouth' `
                      --template-file bicep/services.bicep `
                      --parameters @params/services.prd.json
                  }