trigger:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

pr: none

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

pool: 'Dedicated'

stages: 
- stage: Validation
  jobs:
  - template: jobs/dependency-check.yml@ado-pipeline-templates
    parameters: 
      jobName: 'DependencyCheck'
      failOnCVSS: 4

  - template: jobs/build-net-core-projects.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildNetCoreProjects'
      toolsManifestPath: '$(Build.SourcesDirectory)/.config/dotnet-tools.json'
      useCobertura: true

  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-ado-Personal-Public-devtest'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      jobName: 'ValidateBicepAgainstDevEnvironment'
      azureSubscription: 'spn-ado-Personal-Public-devtest'
      environment: 'dev'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      jobName: 'ValidateBicepAgainstPrdEnvironment'
      azureSubscription: 'spn-ado-Personal-Public-geolocation-prd'
      environment: 'prd'
